# Generated by Django 5.0.2 on 2024-03-09 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 7, 33, 36, 277748, tzinfo=datetime.timezone.utc)),
        ),
    ]
