services:
  back:
    image: ypeskov/djw:0.54
    env_file:
      - ../.env
    container_name: "djw"
#    platform: "linux/amd64"
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./media:/app/media
    restart: always
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=135.181.38.18,localhost,127.0.0.1,[::1]
    depends_on:
      - db-djw
      - redis-djw

  db-djw:
    image: postgres:16.2-alpine
    container_name: Postgres-djw
    restart: always
    environment:
      # POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: djw
    ports:
      - 5432:5432
    volumes:
      - ../dbdata:/var/lib/postgresql/data

  redis-djw:
    image: redis:alpine
    container_name: Redis-djw
    restart: always

  celery:
      image: ypeskov/djw:0.54
#      platform: "linux/amd64"
      env_file:
        - ${APP_ENV_FILE:-../.env}
      command: /bin/sh -c "celery -A djweather worker -l info --concurrency=$${CELERY_WORKER_CONCURRENCY:-4}"
      depends_on:
        - redis-djw

  celery-beat:
    image: ypeskov/djw:0.54
#    platform: "linux/amd64"
    env_file:
      - ${APP_ENV_FILE:-../.env}
    command: poetry run celery -A djweather beat -l info
    depends_on:
      - redis-djw
